### PR TITLE
initial

### PR DESCRIPTION
**Pull request by ribalba**

### CODE REVIEW

**Comment by ArneTR** [comment]
The text is nice and concise. Apart from one small typo "surly => surely" I would publish this unredacted.

However on the tooling side I experienced still many errors and this is not ready yet IMHO.

1. Whenever I change data the table at the bottom gets not cleared but appended

2. The embodied carbon from the old machine mysteriously gets added to the new machine (See example screenshot where I put embodied carbon from the old machine to a high number and the new machine to 0)
Screenshot 2024-08-03 at 6 32 24 PM
=> If that behaviour is intended than I do not understand what the graph shows ...

3. I do not understand when the graph updates. When using the up/down arrows I get instant updates. When typing into the text fields nothing happens. Even If I click enter. Only when also using up/down arrows it seems to apply the cumulative changes.

Here either a *loading circle* or a toast "All changes saved" or a "Update" button would be helpful.

**Comment by ribalba** [comment]
@ArneTR I added the things we talked about. Please see if this makes it clearer to you

**Comment by ArneTR** [comment]
Jap. The two boxes and the break even bar really help in understanding.

Also the infinite additions are gone.

Checked in Chrome and FF and all works.

On mobile the chart is too wide as it has no auto-scaling. Definitely usable, but looks a bit broken as you have to zoom out to use it
photo_2_2024-08-08_14-52-41
photo_1_2024-08-08_14-52-41

**Comment by ribalba** [comment]
@ArneTR fixed on mobile. Pleas review again and then you can merge if you want

**Comment by ArneTR** [comment]
Sweet, looks good.

**Comment by ArneTR** [comment]
@ribalba Please ping Michelle for LinkedIn Posting or draft mini post yourself

**Pull request merged**
